name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Gera uma vez por dia
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: ludivinojosedasilva/snk@v3
        with:
          github_user_name: ludivinojosedasilva
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Commit and push
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

🐍 Adiciona workflow para gerar Snake
